config/routes.rb
Places::Application.routes.draw do

 

  

  

  root to: "sessions#new"
  
  
   
   resources :users do
    	
	
	resources :places do
    		resources :events, on: :member
		
   	end
        
	
   end
 
   resources :places do
    		get :events, on: :member
		
   end

  resources :events

  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"

    
  
   
   
   
   
   
   

   

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place
  attr_accessible :date, :description, :name, :rating, :place_id
  
  validates_presence_of :date, :description, :name
  validates :rating, numericality: {:greater_than=>0, :less_than=>6}, if: "rating.present?"
  
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :events, :dependent => :destroy
  
  attr_accessible :adress, :description, :name, :phone, :user_id
  

  validates_presence_of :name, :adress
  validates_uniqueness_of :name, :adress, :description
  before_validation :clean_name, if: "name.present?"
  before_validation :clean_adress, if: "adress.present?" 

  private
  def clean_name
    self.name = self.name.strip.capitalize
  end
  def clean_adress
    self.adress = self.adress.strip.capitalize
  end

  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :places, :dependent => :destroy
  
  has_secure_password
   
   attr_accessible :email, :username, :password, :password_confirmation
  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email

  def encrypt_password
	if password.present?
  		self.password_salt = BCrypt::Engine.generate.salt
		self.password_hash = BCrypt::Engine.generate.hash_secret(password, password_salt)
	end
  end



  
		 
  
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound

  end
  
  def logged_in?
    current_user != nil
  end
  

  helper_method :current_user, :logged_in?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
	@events=Event.all
  end

  def show
	@event = Event.find(params[:id])
  end

  def new
	@event = Event.new
	
	
  end

  def create
	@event = Event.new(params[:event])
	
    	if @event.save
          redirect_to user_place_event_path(@event, :place_id => @event.place_id, :user_id => Place.find_by_id(@event.place_id).user_id)
    	else
          redirect_to new_user_place_event_path(@event, :place_id => @event.place_id, :user_id => Place.find_by_id(@event.place_id).user_id)
    	end
  end

  def edit
	@event = Event.find(params[:id])
  end

  def update
	
	@event = Event.find(params[:id])
	@event.rating = params[:rating].to_i
    	if @event.update_attributes(params[:event])
          redirect_to user_place_event_path(@event, :place_id => @event.place_id, :user_id => Place.find_by_id(@event.place_id).user_id)
    	else
          redirect_to edit_user_place_event_path(@event, :place_id => @event.place_id, :user_id => Place.find_by_id(@event.place_id).user_id)
    	end
  end


  def destroy
	Event.find_by_id(params[:id]).try(:destroy)
   	redirect_to places_path
  end

  def rate
	@event = Event.find(params[:id])
	
  end

  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
	if current_user == nil
		redirect_to root_path
	else
		@places=Place.all
	end
	
			
  end

  def show
	if current_user == nil
		redirect_to root_path
	else
		@place = Place.find(params[:id])
	end
  end

  def new
	if current_user == nil
		redirect_to root_path
	else
		@place = Place.new
	end
  end

  def create
	if current_user == nil
		redirect_to root_path
	else	
	 	@place = Place.new(params[:place])
	
   	 	if @place.save
        	  redirect_to user_place_path(@place, :user_id => @place.user_id)
    		else
        	  redirect_to new_user_place_path(@place, :user_id => @place.user_id)
    		end
	end  
  end

  def edit
	if current_user == nil
		redirect_to root_path
	else
		@place = Place.find(params[:id])
	end
  end

  def update
	if	
		@place = Place.find(params[:id])
	
	    	if @place.update_attributes(params[:place])	
          		redirect_to user_place_path(@place, :user_id => @place.user_id)
    		else
        		  redirect_to edit_user_place_path(@place, :user_id => @place.user_id)
    		end
	end
  end

  

  def destroy
	if current_user == nil
		redirect_to root_path
	else	
		Place.find_by_id(params[:id]).try(:destroy)
   		redirect_to places_path
	end
  end
  def events
    @events = Place.find_by_id(params[:id]).events
    render 'events/index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  

  def create
    if current_user
	redirect_to current_user_path
    else

	    user = User.find_by_email params[:email]
	    if user && user.authenticate(params[:password])
      		session[:user_id] = user.id
      		redirect_to user_path(user) , notice: "Logged in!"
    	    else
      		redirect_to root_path, notice: "Email or password is invalid"
    	    end
    end
  end


   def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	
		@users=User.all
	end
  

  def show
	
	
	@user = User.find(params[:id])
	
  end

  def new
	if current_user 
		redirect_to root_path
	else
	@user = User.new
	end
  end

  def create
	
		
	@user = User.new(params[:user])
	
    	if @user.save
          redirect_to root_path
    	else
          render :new
    	end
	
  end

  def edit
	if current_user 
		redirect_to root_path
	else	
	@user = User.find(params[:id])
	end
  end

  def update
	@User = User.find(params[:id])
	
     
    	if @user.update_attributes(params[:user])
          redirect_to @user
    	else
          render :edit
    	end
  end

  def destroy
	@user = User.find_by_id(params[:id])
	if current_user == @user 
		
		if @user.try(:destroy)
   			redirect_to root_path, notice: "Your account has been deleted"
		else
			redirect_to @user, notice: "Something Went Wrong!"
		end
	else
		redirect_to current_user, notice: "You are not this user!"
	end
		
		
  end

  def places
    @places = User.find_by_id(params[:id]).places
    render 'places/index'
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<html>
<head>
    <%= stylesheet_link_tag "mystyle.css" %>
  <title>Places</title>
</head>
<body>
   <div id='mycontainer' >  

    <div id='mycenter2' , class='createformcenter'>

      <div id='createform', class='mycontainer2'>

        <%= form_for @event do |f| %>
  
  <% if @event.errors.any? %>
      <h3>Something went wrong!</h3>
      <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  <% end %>


  <p>
    
    <%= f.text_field :name, :placeholder=>'Name' %>
    <br>
    
    <%= f.text_area :description , :placeholder=>'Description', :id=>'eventdescription'%>
    <br>
    <%= f.text_field :date, :placeholder=>'Date'%>
    <%= f.hidden_field :place_id, :value => params[:place_id] %>

    
      
  </p>
   
  <p>

    <span id='place_selection_text'>Place: </span>
    <select name="place_id"  >
      <option value= <%= params[:place_id].to_i %> > <%=Place.find_by_id(params[:place_id]).name %>  </option>
    </select>
    
  
    
  </p>
  <p>
    <%= f.submit :class=>'btn'%>
  </p>
<% end %>

      </div>
    </div>
    </div>
</body>
</html>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Change what you will!</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>

<ol>
  <% @events.each do |event|%>
    
   <li>
      <h3><%= link_to event.name, event %></h3> 
    
      <p>-<%= event.description %><p> 
   </li>
  <% end %>
</ol>

<%= link_to "Add an event", new_event_path %>
<%= link_to "Places", places_path %>

app/views/events/new.html.erb
<h1> New Event! </h1>
<%= render 'form' %>

app/views/events/show.html.erb
<html>
<head>
  <%= stylesheet_link_tag "mystyle.css" %>
  <title>Places</title>
</head>
<body>
  <div id='containerheight'>
    <h1><%= @event.name %> <h1>
    <div id='mycenter2' class='shadow1'>
      <div class='mycontainer2'  id='showplace'>
          <h3><%= @event.description %></h3>

  <div id='eventlist'>
    <ul>
      <div id='listitem'>
        <li> <p>
         Date: <%= @event.date %>
         </p></li>
      </div>
 

    <li><p> Place: <%= (Place.find_by_id(@event.place_id)).name %></p></li>
 <li>
<p>
  
  Your rating: <% if @event.rating %>
      <%= @event.rating %> 
    <% else %>
    <br>
    <br>
      <%= link_to "*", user_place_event_path(@event, :rating => 1), :method => :put , :id=>'eventlink'%>
      <%= link_to "*", user_place_event_path(@event, :rating => 2), :method => :put , :id=>'eventlink'%>
      <%= link_to "*", user_place_event_path(@event, :rating => 3), :method => :put , :id=>'eventlink'%>
      <%= link_to "*", user_place_event_path(@event, :rating => 4), :method => :put , :id=>'eventlink'%>
      <%= link_to "*", user_place_event_path(@event, :rating => 5), :method => :put , :id=>'eventlink'%>
    <% end %>
  
  </p>
 </li>
  
   </ul>
  </div>
  <div>
  <% if current_user.id == Place.find_by_id(@event.place_id).user_id %>
  <%= link_to "Delete", @event, :method => :delete, :confirm => "Are you sure?" , :id=>'eventlink'%>
  <%= link_to "Update", edit_user_place_event_path(@event, :place_id => @event.place_id, :user_id => Place.find_by_id(@event.place_id).user_id ), :id=>'eventlink' %>
  <% end %>

<%= link_to "go to place", user_place_path(Place.find_by_id(@event.place_id), :user_id => Place.find_by_id(@event.place_id).user_id), :id=>'eventlink' %>
      </div>
    </div>
  </div>


</body>
</html>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/home/index.html.erb
<h1>Places!</h1>
<h2>A place to find all your awesome places </h2>
<h3>Log in to proceed</h3>

<%= link_to "Sign Up", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% unless logged_in? %>
  
<% else %>
  Logged in as <%= link_to current_user.username, current_user %>
  <%= link_to "Log out", session_path("current"), method: "delete" %>
<%end%>


<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<html>
<head>
  <%= stylesheet_link_tag "mystyle.css" %>
  <title>Places</title>
</head>
<body>
  <div id='mycontainer' >
    <div id='mycenter' , class='createformcenter'>
      <div id='createform', class='mycontainer2'>
          <p>
    -User: <%=User.find_by_id(params[:user_id]).username %>
</p>

<%= form_for @place do |f| %>
  
  <% if @place.errors.any? %>
      <h3>Something went wrong!</h3>
      <ul>
          <% @place.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  <% end %>


  <p>
    <%= f.text_field :name, :placeholder=>'Name' %>
   <br>
    
    <%= f.text_area :description, :placeholder=>'Description', :id=>'eventdescription'%>
    <br>
    <%= f.text_field :adress, :placeholder=>'Address' %>
   <br>
    <%= f.text_field :phone, :placeholder=>'Phone'%>   
    <%= f.hidden_field :user_id, :value => params[:user_id] , :placeholder=>'Description'%> 
  </p>
  

  <p>
    <%= f.submit  :class=>'btn'%>
  </p>
<% end %>
      </div>
        
    </div>
  </div>

</body>
</html>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/destroy.html.erb
<h1>Places#destroy</h1>
<p>Find me in app/views/places/destroy.html.erb</p>

app/views/places/edit.html.erb
<h1>What's new?</h1>
<%= render 'form' %>

app/views/places/index.html.erb
<html>
<head>
	<%= stylesheet_link_tag "mystyle.css" %>
	<title>Places</title>
</head>
<body>
<div id='containerheight'>
	<h1>Select a place!</h1>
	<div id='mycenter2' class='shadow1'>
		<div id='mybox'  >
			<ul>
  		<% @places.each do |place|%>
    
   		<li>
   		<div id='aplace' class='shadow2'>
   			<h3><%= link_to place.name, user_place_path(place, :user_id => place.user_id) %>
      	</h3> 
    
     	 <p>-<%= place.description %><p> 
   		</div>
      	
  		 </li>

  		<% end %>
		</ul>

		</div>
		
	</div>

</div>
	

</body>
</html>

app/views/places/new.html.erb
<h1>New Place!</h1>
<%= render 'form' %>

app/views/places/show.html.erb
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag "mystyle.css" %>
</head>
<body>
  <div id='containerheight'>
    <h1><%= @place.name %> </h1>
    <div id='mycenter2' class='shadow1'>

      <div class='mycontainer2'  id='showplace'>
<div id='eventdescription'>
            <h3><%= @place.description %></h3>
<h3> current user <%= current_user.username %> </h3>
<ol>
  <p>
  -Adress: <%= @place.adress %>
  </p>
  <p>
  -Phone: <%= @place.phone %>
  </p>
  <p>
  -User who added this place: <%= link_to User.find_by_id(@place.user_id).username, User.find_by_id(@place.user_id) %>
  </p>
  <% if current_user.id == @place.user_id %>
  <%= link_to "Delete", @place, :method => :delete, :confirm => "Are you sure?" %>
  <% end %>
</ol>
</div>

<% if @place.events.present? %>
   <div id='eventlist'>
  <ul>
  <h2> Events! </h2>
  <% @place.events.each do |event|%>
   
       <li>
     
          <h3><%= link_to event.name,  user_place_event_path(event, :place_id =>event.place_id, :user_id => Place.find_by_id(event.place_id).user_id) %></h3> 
    
          <p>-<%= event.description %><p> 
      
    
   </li>
  <% end %>
  </div> 
</ul>

<% end %>

</div>



  </div>
  <% if current_user.id == @place.user_id %>

<div id='eventlinks'> 
      <%= link_to "Add an event  |", new_user_place_event_path(:place_id => @place.id), :class=>"lightcolor" %>

<%= link_to "Update  |", edit_user_place_path(@place, :user_id => @place.user_id), :class=>"lightcolor" %>
<% end %>
<%= link_to "Places", places_path, :class=>"lightcolor" %>

</div>
    </div>
     

      </div>
         


</body>
</html>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>

app/views/users/_form.html.erb
<html>
<head>
  <%= stylesheet_link_tag "mystyle.css" %>
  <title>Places</title>
</head>
<body>
    <div id='mycontainer3' >  

    <div id='mycenter' , class='createformcenter'>

      <div id='createform', class='mycontainer2'>

        <%= link_to "back", root_path %>
<%= form_for @user do |f| %>
  
  <% if @user.errors.any? %>
      <h3>Something went wrong!</h3>
      <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  <% end %>


  <p>
   
    <%= f.text_field :username, :placeholder=>'Username' %>
    <br>
    
    <%= f.text_field :email, :placeholder=>'Email' %>   
    <div class="field">
     
      <%= f.password_field :password, :placeholder=>'password' ,:id=>'userpass' %>
    </div>
    <div class="field">
     
     <%= f.password_field :password_confirmation, :placeholder=>'password confirmation',:id=>'userpass' %>
    </div>
 
  </p>
  <p>
    <%= f.submit :class=>'btn' %>
  </p>
<% end %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>What's new?</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>New User!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<html>
<head>
  <%= stylesheet_link_tag "mystyle.css" %>
  <title>Places</title>
</head>
<body>
<%= flash[:warning] || flash[:notice] %>
    <div id='containerheight'>
       <h1><%= @user.username %> </h1>
        <div id='mycenter2' class='shadow1'>
           

<div class='mycontainer2'  id='showplace'>

<ol>
  <p>
  Email: <%= @user.email %>
  </p>
  
  <% if current_user.id == @user.id %>
  <%= link_to "Delete Account", @user, :method => :delete, :confirm => "Are you sure?" %>
  
  <%= link_to "Sign Out", log_out_path(@user) %>
  <% end %>
  
 
</ol>


<% if @user.places.present? %>
  
  <ol>
  <h2> Places <%= @user.username %> has added! </h2>
  <% @user.places.each do |place|%>
    
   <li>
      <h3><%= link_to place.name, user_place_path(place, :user_id => place.user_id) %></h3> 
    
      <p>-<%= place.description %><p> 
   </li>
  <% end %>
</ol>
<% end %>
<% if current_user.id == @user.id %>
<%= link_to "Add a place", new_user_place_path(:user_id => @user.id)  %>

<%= link_to "Update", edit_user_path(@user) %>
<% end %>

<%= link_to "Places", places_path %>


</div>

        </div>

    </div>

</body>
</html>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>